// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh3skpNNJa09bJzE9MOsqk0EahbMITuMM',
    appId: '1:723098412653:web:6382c526e7adf67d868164',
    messagingSenderId: '723098412653',
    projectId: 'jobmailer-2a114',
    authDomain: 'jobmailer-2a114.firebaseapp.com',
    storageBucket: 'jobmailer-2a114.firebasestorage.app',
    measurementId: 'G-B8GY04XNJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWb-U7rzE4fmefRzco2NMwPb_4e-bCvcM',
    appId: '1:723098412653:android:66230c32c9d3ce23868164',
    messagingSenderId: '723098412653',
    projectId: 'jobmailer-2a114',
    storageBucket: 'jobmailer-2a114.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO-8gYFZ2YAwQIzdFV-cfk0SPOVKr3aME',
    appId: '1:723098412653:ios:164ca286d57c0e15868164',
    messagingSenderId: '723098412653',
    projectId: 'jobmailer-2a114',
    storageBucket: 'jobmailer-2a114.firebasestorage.app',
    androidClientId: '723098412653-qg2fukhlpest3k0tchjhlcfm6ajd0hcr.apps.googleusercontent.com',
    iosClientId: '723098412653-789beim3jd7pr6cl6j5k3j94b0kbpre3.apps.googleusercontent.com',
    iosBundleId: 'com.example.autojobmail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO-8gYFZ2YAwQIzdFV-cfk0SPOVKr3aME',
    appId: '1:723098412653:ios:164ca286d57c0e15868164',
    messagingSenderId: '723098412653',
    projectId: 'jobmailer-2a114',
    storageBucket: 'jobmailer-2a114.firebasestorage.app',
    androidClientId: '723098412653-qg2fukhlpest3k0tchjhlcfm6ajd0hcr.apps.googleusercontent.com',
    iosClientId: '723098412653-789beim3jd7pr6cl6j5k3j94b0kbpre3.apps.googleusercontent.com',
    iosBundleId: 'com.example.autojobmail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh3skpNNJa09bJzE9MOsqk0EahbMITuMM',
    appId: '1:723098412653:web:36c938a2501c2ea0868164',
    messagingSenderId: '723098412653',
    projectId: 'jobmailer-2a114',
    authDomain: 'jobmailer-2a114.firebaseapp.com',
    storageBucket: 'jobmailer-2a114.firebasestorage.app',
    measurementId: 'G-9W93GYSFXW',
  );
}
